# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zyy/workspace/myfiber

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zyy/workspace/myfiber

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyy/workspace/myfiber/CMakeFiles /home/zyy/workspace/myfiber/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyy/workspace/myfiber/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myfiber

# Build rule for target.
myfiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myfiber
.PHONY : myfiber

# fast build rule for target.
myfiber/fast:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/build
.PHONY : myfiber/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

myfiber/address.o: myfiber/address.cpp.o
.PHONY : myfiber/address.o

# target to build an object file
myfiber/address.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/address.cpp.o
.PHONY : myfiber/address.cpp.o

myfiber/address.i: myfiber/address.cpp.i
.PHONY : myfiber/address.i

# target to preprocess a source file
myfiber/address.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/address.cpp.i
.PHONY : myfiber/address.cpp.i

myfiber/address.s: myfiber/address.cpp.s
.PHONY : myfiber/address.s

# target to generate assembly for a file
myfiber/address.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/address.cpp.s
.PHONY : myfiber/address.cpp.s

myfiber/config.o: myfiber/config.cpp.o
.PHONY : myfiber/config.o

# target to build an object file
myfiber/config.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/config.cpp.o
.PHONY : myfiber/config.cpp.o

myfiber/config.i: myfiber/config.cpp.i
.PHONY : myfiber/config.i

# target to preprocess a source file
myfiber/config.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/config.cpp.i
.PHONY : myfiber/config.cpp.i

myfiber/config.s: myfiber/config.cpp.s
.PHONY : myfiber/config.s

# target to generate assembly for a file
myfiber/config.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/config.cpp.s
.PHONY : myfiber/config.cpp.s

myfiber/fd_manager.o: myfiber/fd_manager.cpp.o
.PHONY : myfiber/fd_manager.o

# target to build an object file
myfiber/fd_manager.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/fd_manager.cpp.o
.PHONY : myfiber/fd_manager.cpp.o

myfiber/fd_manager.i: myfiber/fd_manager.cpp.i
.PHONY : myfiber/fd_manager.i

# target to preprocess a source file
myfiber/fd_manager.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/fd_manager.cpp.i
.PHONY : myfiber/fd_manager.cpp.i

myfiber/fd_manager.s: myfiber/fd_manager.cpp.s
.PHONY : myfiber/fd_manager.s

# target to generate assembly for a file
myfiber/fd_manager.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/fd_manager.cpp.s
.PHONY : myfiber/fd_manager.cpp.s

myfiber/fiber.o: myfiber/fiber.cpp.o
.PHONY : myfiber/fiber.o

# target to build an object file
myfiber/fiber.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/fiber.cpp.o
.PHONY : myfiber/fiber.cpp.o

myfiber/fiber.i: myfiber/fiber.cpp.i
.PHONY : myfiber/fiber.i

# target to preprocess a source file
myfiber/fiber.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/fiber.cpp.i
.PHONY : myfiber/fiber.cpp.i

myfiber/fiber.s: myfiber/fiber.cpp.s
.PHONY : myfiber/fiber.s

# target to generate assembly for a file
myfiber/fiber.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/fiber.cpp.s
.PHONY : myfiber/fiber.cpp.s

myfiber/hook.o: myfiber/hook.cpp.o
.PHONY : myfiber/hook.o

# target to build an object file
myfiber/hook.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/hook.cpp.o
.PHONY : myfiber/hook.cpp.o

myfiber/hook.i: myfiber/hook.cpp.i
.PHONY : myfiber/hook.i

# target to preprocess a source file
myfiber/hook.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/hook.cpp.i
.PHONY : myfiber/hook.cpp.i

myfiber/hook.s: myfiber/hook.cpp.s
.PHONY : myfiber/hook.s

# target to generate assembly for a file
myfiber/hook.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/hook.cpp.s
.PHONY : myfiber/hook.cpp.s

myfiber/http/http.o: myfiber/http/http.cpp.o
.PHONY : myfiber/http/http.o

# target to build an object file
myfiber/http/http.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http.cpp.o
.PHONY : myfiber/http/http.cpp.o

myfiber/http/http.i: myfiber/http/http.cpp.i
.PHONY : myfiber/http/http.i

# target to preprocess a source file
myfiber/http/http.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http.cpp.i
.PHONY : myfiber/http/http.cpp.i

myfiber/http/http.s: myfiber/http/http.cpp.s
.PHONY : myfiber/http/http.s

# target to generate assembly for a file
myfiber/http/http.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http.cpp.s
.PHONY : myfiber/http/http.cpp.s

myfiber/http/http11_parser.o: myfiber/http/http11_parser.cpp.o
.PHONY : myfiber/http/http11_parser.o

# target to build an object file
myfiber/http/http11_parser.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http11_parser.cpp.o
.PHONY : myfiber/http/http11_parser.cpp.o

myfiber/http/http11_parser.i: myfiber/http/http11_parser.cpp.i
.PHONY : myfiber/http/http11_parser.i

# target to preprocess a source file
myfiber/http/http11_parser.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http11_parser.cpp.i
.PHONY : myfiber/http/http11_parser.cpp.i

myfiber/http/http11_parser.s: myfiber/http/http11_parser.cpp.s
.PHONY : myfiber/http/http11_parser.s

# target to generate assembly for a file
myfiber/http/http11_parser.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http11_parser.cpp.s
.PHONY : myfiber/http/http11_parser.cpp.s

myfiber/http/http_parser.o: myfiber/http/http_parser.cpp.o
.PHONY : myfiber/http/http_parser.o

# target to build an object file
myfiber/http/http_parser.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http_parser.cpp.o
.PHONY : myfiber/http/http_parser.cpp.o

myfiber/http/http_parser.i: myfiber/http/http_parser.cpp.i
.PHONY : myfiber/http/http_parser.i

# target to preprocess a source file
myfiber/http/http_parser.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http_parser.cpp.i
.PHONY : myfiber/http/http_parser.cpp.i

myfiber/http/http_parser.s: myfiber/http/http_parser.cpp.s
.PHONY : myfiber/http/http_parser.s

# target to generate assembly for a file
myfiber/http/http_parser.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/http_parser.cpp.s
.PHONY : myfiber/http/http_parser.cpp.s

myfiber/http/httpclient_parser.o: myfiber/http/httpclient_parser.cpp.o
.PHONY : myfiber/http/httpclient_parser.o

# target to build an object file
myfiber/http/httpclient_parser.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/httpclient_parser.cpp.o
.PHONY : myfiber/http/httpclient_parser.cpp.o

myfiber/http/httpclient_parser.i: myfiber/http/httpclient_parser.cpp.i
.PHONY : myfiber/http/httpclient_parser.i

# target to preprocess a source file
myfiber/http/httpclient_parser.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/httpclient_parser.cpp.i
.PHONY : myfiber/http/httpclient_parser.cpp.i

myfiber/http/httpclient_parser.s: myfiber/http/httpclient_parser.cpp.s
.PHONY : myfiber/http/httpclient_parser.s

# target to generate assembly for a file
myfiber/http/httpclient_parser.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/http/httpclient_parser.cpp.s
.PHONY : myfiber/http/httpclient_parser.cpp.s

myfiber/iomanager.o: myfiber/iomanager.cpp.o
.PHONY : myfiber/iomanager.o

# target to build an object file
myfiber/iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/iomanager.cpp.o
.PHONY : myfiber/iomanager.cpp.o

myfiber/iomanager.i: myfiber/iomanager.cpp.i
.PHONY : myfiber/iomanager.i

# target to preprocess a source file
myfiber/iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/iomanager.cpp.i
.PHONY : myfiber/iomanager.cpp.i

myfiber/iomanager.s: myfiber/iomanager.cpp.s
.PHONY : myfiber/iomanager.s

# target to generate assembly for a file
myfiber/iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/iomanager.cpp.s
.PHONY : myfiber/iomanager.cpp.s

myfiber/log.o: myfiber/log.cpp.o
.PHONY : myfiber/log.o

# target to build an object file
myfiber/log.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/log.cpp.o
.PHONY : myfiber/log.cpp.o

myfiber/log.i: myfiber/log.cpp.i
.PHONY : myfiber/log.i

# target to preprocess a source file
myfiber/log.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/log.cpp.i
.PHONY : myfiber/log.cpp.i

myfiber/log.s: myfiber/log.cpp.s
.PHONY : myfiber/log.s

# target to generate assembly for a file
myfiber/log.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/log.cpp.s
.PHONY : myfiber/log.cpp.s

myfiber/scheduler.o: myfiber/scheduler.cpp.o
.PHONY : myfiber/scheduler.o

# target to build an object file
myfiber/scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/scheduler.cpp.o
.PHONY : myfiber/scheduler.cpp.o

myfiber/scheduler.i: myfiber/scheduler.cpp.i
.PHONY : myfiber/scheduler.i

# target to preprocess a source file
myfiber/scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/scheduler.cpp.i
.PHONY : myfiber/scheduler.cpp.i

myfiber/scheduler.s: myfiber/scheduler.cpp.s
.PHONY : myfiber/scheduler.s

# target to generate assembly for a file
myfiber/scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/scheduler.cpp.s
.PHONY : myfiber/scheduler.cpp.s

myfiber/socket.o: myfiber/socket.cpp.o
.PHONY : myfiber/socket.o

# target to build an object file
myfiber/socket.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/socket.cpp.o
.PHONY : myfiber/socket.cpp.o

myfiber/socket.i: myfiber/socket.cpp.i
.PHONY : myfiber/socket.i

# target to preprocess a source file
myfiber/socket.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/socket.cpp.i
.PHONY : myfiber/socket.cpp.i

myfiber/socket.s: myfiber/socket.cpp.s
.PHONY : myfiber/socket.s

# target to generate assembly for a file
myfiber/socket.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/socket.cpp.s
.PHONY : myfiber/socket.cpp.s

myfiber/tcp_server.o: myfiber/tcp_server.cpp.o
.PHONY : myfiber/tcp_server.o

# target to build an object file
myfiber/tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/tcp_server.cpp.o
.PHONY : myfiber/tcp_server.cpp.o

myfiber/tcp_server.i: myfiber/tcp_server.cpp.i
.PHONY : myfiber/tcp_server.i

# target to preprocess a source file
myfiber/tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/tcp_server.cpp.i
.PHONY : myfiber/tcp_server.cpp.i

myfiber/tcp_server.s: myfiber/tcp_server.cpp.s
.PHONY : myfiber/tcp_server.s

# target to generate assembly for a file
myfiber/tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/tcp_server.cpp.s
.PHONY : myfiber/tcp_server.cpp.s

myfiber/thread.o: myfiber/thread.cpp.o
.PHONY : myfiber/thread.o

# target to build an object file
myfiber/thread.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/thread.cpp.o
.PHONY : myfiber/thread.cpp.o

myfiber/thread.i: myfiber/thread.cpp.i
.PHONY : myfiber/thread.i

# target to preprocess a source file
myfiber/thread.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/thread.cpp.i
.PHONY : myfiber/thread.cpp.i

myfiber/thread.s: myfiber/thread.cpp.s
.PHONY : myfiber/thread.s

# target to generate assembly for a file
myfiber/thread.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/thread.cpp.s
.PHONY : myfiber/thread.cpp.s

myfiber/timer.o: myfiber/timer.cpp.o
.PHONY : myfiber/timer.o

# target to build an object file
myfiber/timer.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/timer.cpp.o
.PHONY : myfiber/timer.cpp.o

myfiber/timer.i: myfiber/timer.cpp.i
.PHONY : myfiber/timer.i

# target to preprocess a source file
myfiber/timer.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/timer.cpp.i
.PHONY : myfiber/timer.cpp.i

myfiber/timer.s: myfiber/timer.cpp.s
.PHONY : myfiber/timer.s

# target to generate assembly for a file
myfiber/timer.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/timer.cpp.s
.PHONY : myfiber/timer.cpp.s

myfiber/util.o: myfiber/util.cpp.o
.PHONY : myfiber/util.o

# target to build an object file
myfiber/util.cpp.o:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/util.cpp.o
.PHONY : myfiber/util.cpp.o

myfiber/util.i: myfiber/util.cpp.i
.PHONY : myfiber/util.i

# target to preprocess a source file
myfiber/util.cpp.i:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/util.cpp.i
.PHONY : myfiber/util.cpp.i

myfiber/util.s: myfiber/util.cpp.s
.PHONY : myfiber/util.s

# target to generate assembly for a file
myfiber/util.cpp.s:
	$(MAKE) -f CMakeFiles/myfiber.dir/build.make CMakeFiles/myfiber.dir/myfiber/util.cpp.s
.PHONY : myfiber/util.cpp.s

tests/test.o: tests/test.cpp.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

tests/test_address.o: tests/test_address.cpp.o
.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cpp.o:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.o
.PHONY : tests/test_address.cpp.o

tests/test_address.i: tests/test_address.cpp.i
.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cpp.i:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.i
.PHONY : tests/test_address.cpp.i

tests/test_address.s: tests/test_address.cpp.s
.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cpp.s:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.s
.PHONY : tests/test_address.cpp.s

tests/test_config.o: tests/test_config.cpp.o
.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cpp.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.o
.PHONY : tests/test_config.cpp.o

tests/test_config.i: tests/test_config.cpp.i
.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cpp.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.i
.PHONY : tests/test_config.cpp.i

tests/test_config.s: tests/test_config.cpp.s
.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cpp.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.s
.PHONY : tests/test_config.cpp.s

tests/test_fiber.o: tests/test_fiber.cpp.o
.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cpp.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.o
.PHONY : tests/test_fiber.cpp.o

tests/test_fiber.i: tests/test_fiber.cpp.i
.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cpp.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.i
.PHONY : tests/test_fiber.cpp.i

tests/test_fiber.s: tests/test_fiber.cpp.s
.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cpp.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.s
.PHONY : tests/test_fiber.cpp.s

tests/test_hook.o: tests/test_hook.cpp.o
.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cpp.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.o
.PHONY : tests/test_hook.cpp.o

tests/test_hook.i: tests/test_hook.cpp.i
.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cpp.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.i
.PHONY : tests/test_hook.cpp.i

tests/test_hook.s: tests/test_hook.cpp.s
.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cpp.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.s
.PHONY : tests/test_hook.cpp.s

tests/test_http_parser.o: tests/test_http_parser.cpp.o
.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.o
.PHONY : tests/test_http_parser.cpp.o

tests/test_http_parser.i: tests/test_http_parser.cpp.i
.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.i
.PHONY : tests/test_http_parser.cpp.i

tests/test_http_parser.s: tests/test_http_parser.cpp.s
.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.s
.PHONY : tests/test_http_parser.cpp.s

tests/test_iomanager.o: tests/test_iomanager.cpp.o
.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.o
.PHONY : tests/test_iomanager.cpp.o

tests/test_iomanager.i: tests/test_iomanager.cpp.i
.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.i
.PHONY : tests/test_iomanager.cpp.i

tests/test_iomanager.s: tests/test_iomanager.cpp.s
.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.s
.PHONY : tests/test_iomanager.cpp.s

tests/test_scheduler.o: tests/test_scheduler.cpp.o
.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.o
.PHONY : tests/test_scheduler.cpp.o

tests/test_scheduler.i: tests/test_scheduler.cpp.i
.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.i
.PHONY : tests/test_scheduler.cpp.i

tests/test_scheduler.s: tests/test_scheduler.cpp.s
.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.s
.PHONY : tests/test_scheduler.cpp.s

tests/test_socket.o: tests/test_socket.cpp.o
.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cpp.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.o
.PHONY : tests/test_socket.cpp.o

tests/test_socket.i: tests/test_socket.cpp.i
.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cpp.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.i
.PHONY : tests/test_socket.cpp.i

tests/test_socket.s: tests/test_socket.cpp.s
.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cpp.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.s
.PHONY : tests/test_socket.cpp.s

tests/test_tcp_server.o: tests/test_tcp_server.cpp.o
.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.o
.PHONY : tests/test_tcp_server.cpp.o

tests/test_tcp_server.i: tests/test_tcp_server.cpp.i
.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.i
.PHONY : tests/test_tcp_server.cpp.i

tests/test_tcp_server.s: tests/test_tcp_server.cpp.s
.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.s
.PHONY : tests/test_tcp_server.cpp.s

tests/test_thread.o: tests/test_thread.cpp.o
.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cpp.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.o
.PHONY : tests/test_thread.cpp.o

tests/test_thread.i: tests/test_thread.cpp.i
.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cpp.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.i
.PHONY : tests/test_thread.cpp.i

tests/test_thread.s: tests/test_thread.cpp.s
.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cpp.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.s
.PHONY : tests/test_thread.cpp.s

tests/test_util.o: tests/test_util.cpp.o
.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cpp.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.o
.PHONY : tests/test_util.cpp.o

tests/test_util.i: tests/test_util.cpp.i
.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cpp.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.i
.PHONY : tests/test_util.cpp.i

tests/test_util.s: tests/test_util.cpp.s
.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cpp.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.s
.PHONY : tests/test_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... myfiber"
	@echo "... test"
	@echo "... test_address"
	@echo "... test_config"
	@echo "... test_fiber"
	@echo "... test_hook"
	@echo "... test_http_parser"
	@echo "... test_iomanager"
	@echo "... test_scheduler"
	@echo "... test_socket"
	@echo "... test_tcp_server"
	@echo "... test_thread"
	@echo "... test_util"
	@echo "... myfiber/address.o"
	@echo "... myfiber/address.i"
	@echo "... myfiber/address.s"
	@echo "... myfiber/config.o"
	@echo "... myfiber/config.i"
	@echo "... myfiber/config.s"
	@echo "... myfiber/fd_manager.o"
	@echo "... myfiber/fd_manager.i"
	@echo "... myfiber/fd_manager.s"
	@echo "... myfiber/fiber.o"
	@echo "... myfiber/fiber.i"
	@echo "... myfiber/fiber.s"
	@echo "... myfiber/hook.o"
	@echo "... myfiber/hook.i"
	@echo "... myfiber/hook.s"
	@echo "... myfiber/http/http.o"
	@echo "... myfiber/http/http.i"
	@echo "... myfiber/http/http.s"
	@echo "... myfiber/http/http11_parser.o"
	@echo "... myfiber/http/http11_parser.i"
	@echo "... myfiber/http/http11_parser.s"
	@echo "... myfiber/http/http_parser.o"
	@echo "... myfiber/http/http_parser.i"
	@echo "... myfiber/http/http_parser.s"
	@echo "... myfiber/http/httpclient_parser.o"
	@echo "... myfiber/http/httpclient_parser.i"
	@echo "... myfiber/http/httpclient_parser.s"
	@echo "... myfiber/iomanager.o"
	@echo "... myfiber/iomanager.i"
	@echo "... myfiber/iomanager.s"
	@echo "... myfiber/log.o"
	@echo "... myfiber/log.i"
	@echo "... myfiber/log.s"
	@echo "... myfiber/scheduler.o"
	@echo "... myfiber/scheduler.i"
	@echo "... myfiber/scheduler.s"
	@echo "... myfiber/socket.o"
	@echo "... myfiber/socket.i"
	@echo "... myfiber/socket.s"
	@echo "... myfiber/tcp_server.o"
	@echo "... myfiber/tcp_server.i"
	@echo "... myfiber/tcp_server.s"
	@echo "... myfiber/thread.o"
	@echo "... myfiber/thread.i"
	@echo "... myfiber/thread.s"
	@echo "... myfiber/timer.o"
	@echo "... myfiber/timer.i"
	@echo "... myfiber/timer.s"
	@echo "... myfiber/util.o"
	@echo "... myfiber/util.i"
	@echo "... myfiber/util.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

